app.version=${project.version}
app.name=${project.artifactId}
default-symbol=2330
default-api-key=OWQxZGI5YWItOTNmZS00ZmVmLWFkNDEtZDFlNzUxMmRmOTNlIDk1OTVjNjU1LTRhN2ItNGUzZi05MTEwLTA3YjMzOTZmNzhhMw==
default-day=30